apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources: # constrain what a container is allowed to run in terms of memory and cpu resources
          limits:
            memory: "128Mi" #128 MB
            cpu: "200m" #millicpu (.2 cpu or 20% of the cpu)

# kubectl create -f nginx-deployment.pod.yml --save-config

# kubectl get deployment --show-labels

# kubectl scale deployment [deployment-name] -- replicas=5
# kubectl scale -f file.deployment.yml --replicas=5



# NAME                            READY   STATUS    RESTARTS   AGE
# pod/my-nginx-5bb9b897c8-mz7kd   1/1     Running   0          94s
# pod/my-nginx-5bb9b897c8-vtl4q   1/1     Running   0          94s
# pod/my-nginx-5bb9b897c8-z484w   1/1     Running   0          94s

# NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
# service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   5h17m

# NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
# deployment.apps/my-nginx   3/3     3            3           95s

# NAME                                  DESIRED   CURRENT   READY   AGE
# replicaset.apps/my-nginx-5bb9b897c8   3         3         3       94s


# kubectl describe deployment my-nginx

# Name:                   my-nginx
# Namespace:              default
# CreationTimestamp:      Sat, 21 Aug 2021 23:09:18 -0500
# Labels:                 app=my-nginx
# Annotations:            deployment.kubernetes.io/revision: 1
# Selector:               app=my-nginx
# Replicas:               3 desired | 3 updated | 3 total | 3 available | 0 unavailable
# StrategyType:           RollingUpdate
# MinReadySeconds:        0
# RollingUpdateStrategy:  25% max unavailable, 25% max surge
# Pod Template:
#   Labels:  app=my-nginx
#   Containers:
#    my-nginx:
#     Image:      nginx:alpine
#     Port:       80/TCP
#     Host Port:  0/TCP
#     Limits:
#       cpu:        200m
#       memory:     128Mi
#     Environment:  <none>
#     Mounts:       <none>
#   Volumes:        <none>
# Conditions:
#   Type           Status  Reason
#   ----           ------  ------
#   Available      True    MinimumReplicasAvailable
#   Progressing    True    NewReplicaSetAvailable
# OldReplicaSets:  <none>
# NewReplicaSet:   my-nginx-5bb9b897c8 (3/3 replicas created)
# Events:
#   Type    Reason             Age   From                   Message
#   ----    ------             ----  ----                   -------
#   Normal  ScalingReplicaSet  46m   deployment-controller  Scaled up replica set my-nginx-5bb9b897c8 to 3



# kubectl get deployment

# kubectl get deployments --show-labels

# NAME       READY   UP-TO-DATE   AVAILABLE   AGE   LABELS
# my-nginx   3/3     3            3           50m   app=my-nginx


# kubectl get deployments -l app=my-nginx
# NAME       READY   UP-TO-DATE   AVAILABLE   AGE
# my-nginx   3/3     3            3           51m


# kubectl get all

#kubectl scale -f nginx-deployment.pod.yml --replicas=6
# deployment.apps/my-nginx scaled


# kubectl get all
# NAME                            READY   STATUS    RESTARTS   AGE
# pod/my-nginx-5bb9b897c8-2kgzz   1/1     Running   0          18s
# pod/my-nginx-5bb9b897c8-8dm9h   1/1     Running   0          18s
# pod/my-nginx-5bb9b897c8-mz7kd   1/1     Running   0          53m
# pod/my-nginx-5bb9b897c8-rflsh   1/1     Running   0          18s
# pod/my-nginx-5bb9b897c8-vtl4q   1/1     Running   0          53m
# pod/my-nginx-5bb9b897c8-z484w   1/1     Running   0          53m

# NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
# service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   6h10m

# NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
# deployment.apps/my-nginx   6/6     6            6           53m

# NAME                                  DESIRED   CURRENT   READY   AGE
# replicaset.apps/my-nginx-5bb9b897c8   6         6         6       53m


# kubectl delete -f nginx-deployment.pod.yml
# deployment.apps "my-nginx" deleted

# C:\Users\lilyx\Kubernetes_OpenShift_Practice\Kubernetes_for_Developers_Pluralsight>kubectl get all
# NAME                            READY   STATUS        RESTARTS   AGE
# pod/my-nginx-5bb9b897c8-2kgzz   0/1     Terminating   0          108s
# pod/my-nginx-5bb9b897c8-8dm9h   0/1     Terminating   0          108s
# pod/my-nginx-5bb9b897c8-mz7kd   0/1     Terminating   0          55m
# pod/my-nginx-5bb9b897c8-rflsh   0/1     Terminating   0          108s
# pod/my-nginx-5bb9b897c8-vtl4q   0/1     Terminating   0          55m
# pod/my-nginx-5bb9b897c8-z484w   0/1     Terminating   0          55m

# NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
# service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   6h11m


# create, describe, apply, get deployments --show-labels, -l app=my-nginx