apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  replicas: 3
  minReadySeconds:  10 # we would like to wait for the pod, to make sure the container hasn't crashed for 10 seconds, then start to get traffic, else we reschedule
  selector: # matches our selector in template
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources: